services:
  _defaults:
    public: true

  symfonymodule_controller:
    class: SymfonyModule\Controller\Admin\AdminSymfonyModuleController
    arguments:
      - '@doctrine.dbal.default_connection'
      - 'doctrine.cache.provider'
      - 'doctrine.orm.entity_manager'

  symfonymodule_entity:
    class: SymfonyModule\Entity\SymfonyModule
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  symfonymodule_repository:
    class: SymfonyModule\Repository\SymfonyModuleRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      
  ### Manager
  symfonymodule.manager.manager_trait:
    class: SymfonyModule\Manager\SymfonyModuleManagerTrait
