admin_index:
  path: symfonymodule/admin/index/
  methods: [GET, POST]
  defaults:
    _controller: 'SymfonyModule\Controller\Admin\AdminSymfonyModuleController::index'
    _legacy_controller: 'AdminSymfonyModuleController'
    _legacy_link: 'AdminSymfonyModuleController'