symfonymodule_admin:
  path: symfonymodule/admin/index/
  methods: [GET, POST]
  defaults:
    _controller: 'SymfonyModule\Controller\Admin\AdminSymfonyModuleController::symfonyModuleIndex'
    _legacy_controller: 'AdminSymfonyModuleController'
    _legacy_link: 'AdminSymfonyModuleController'