services:
  _defaults:
    public: true

  symfonymodule.controller:
    class: SymfonyModule\Controller\Admin\AdminSymfonyModuleController
    arguments:
      - '@doctrine.dbal.default_connection'
      - 'doctrine.cache.provider'
      - 'doctrine.orm.entity_manager'

  symfonymodule.entity:
    class: SymfonyModule\Entity\SymfonyModule
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  symfonymodule.repository:
    class: SymfonyModule\Repository\SymfonyModuleRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'