services:
  _defaults:
    public: true

  symfonymodule_repository:
    class: SymfonyModule\Repository\SymfonyModuleRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
